title: My Blog
email: your-email@example.com
description: >-
  A minimalist blog based on Minimal Mistakes.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://username.github.io" # the base hostname & protocol for your site

theme: minimal-mistakes-jekyll

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Minimal Mistakes settings
author:
  name: Your Name
  avatar: "/assets/images/avatar.png"
  bio: "Your bio goes here."
  location: "Your location"
  email: your-email@example.com
  links:
    - label: "GitHub"
      url: "https://github.com/username"

defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
